### ISSUE TITLE
Use https links in cheatsheet

### ISSUE THREAD

**Issue by puredanger** [jafingerhut/jafingerhut.github.com#8]
Currently, I think all of the links in the cheatsheet are http, although https is supported for nearly all of them.

The only ones I know of that *aren't* https are: http://edn-format.org and http://www.regular-expressions.info.

**Comment by jafingerhut** [comment]
Fixed with this commit in this repo: https://github.com/jafingerhut/jafingerhut.github.com/commit/0b7d5b195402ae40d26f7aa0b9cace19317ae3ec

based upon this update to v39 of the cheatsheet generator: https://github.com/jafingerhut/clojure-cheatsheets/commit/27e2e9c160b7cda6dc874e9207f8cc5947fcb670

Changelog entries for v38 and v39 updates here: https://github.com/jafingerhut/clojure-cheatsheets/blob/master/src/clj-jvm/CHANGELOG.txt
